# Generated by Django 2.0.4 on 2018-04-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180409_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
